name: Release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Publish
        run: dotnet publish Noticer/noticer.csproj -c Release -o publish

      - name: Upload asset
        run: gh release upload ${{ github.ref_name }} publish/noticer.exe
        env:
          GH_TOKEN: ${{ github.token }}
